// Writes config.yaml from contracts/deployments/<network>.json so contract addresses and start
// blocks have a single source of truth. BEAM_NETWORK selects the deployment (default: testnet).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const network = process.env.BEAM_NETWORK ?? "testnet";
const deploymentPath = join(here, "..", "..", "contracts", "deployments", `${network}.json`);
const d = JSON.parse(readFileSync(deploymentPath, "utf8"));

for (const name of ["BeamGifts", "BeamClaims"]) {
  if (!d[name]?.address || !Number.isInteger(d[name]?.block)) {
    throw new Error(`${deploymentPath}: ${name}.address and ${name}.block are required`);
  }
}

const config = `# Generated by scripts/write-config.mjs from contracts/deployments/${network}.json. Do not edit.
name: beam-indexer
disable_default_cross_chain: true
description: Beam live gifts on Monad
handlers: src/handlers
address_format: lowercase
field_selection:
  transaction_fields:
    - hash

contracts:
  - name: BeamGifts
    events:
      - event: "GiftSent(address indexed from, address indexed to, uint256 amount, string displayName, string message, uint16 actionCode, uint64 ts)"
      - event: "GiftSplit(address indexed from, address[] recipients, uint256[] amounts, uint64 ts)"
  - name: BeamClaims
    events:
      - event: "ChatterGiftSent(bytes32 indexed dropId, address indexed from, uint256 amount, string recipientLabel, string displayName, string message, uint16 actionCode, uint64 expiry, uint64 ts)"
      - event: "BombSent(address indexed from, uint256 pool, uint32 slots, bytes32 indexed bombId, string displayName, string message, uint16 actionCode, uint64 expiry, uint64 ts)"
      - event: "Claimed(bytes32 indexed dropId, uint32 slot, address indexed recipient, uint256 amount, uint64 ts)"
      - event: "Reclaimed(bytes32 indexed dropId, address indexed sender, uint256 amount, bool expired, uint64 ts)"

chains:
  - id: ${d.chainId}
    start_block: ${Math.min(d.BeamGifts.block, d.BeamClaims.block)}
    contracts:
      - name: BeamGifts
        address: "${d.BeamGifts.address}"
        start_block: ${d.BeamGifts.block}
      - name: BeamClaims
        address: "${d.BeamClaims.address}"
        start_block: ${d.BeamClaims.block}
`;

writeFileSync(join(here, "..", "config.yaml"), config);
console.log(`config.yaml written for ${network} (chain ${d.chainId})`);
