// Writes config.yaml from contracts/deployments/<network>.json so contract addresses and start
// blocks have a single source of truth. BEAM_NETWORK selects the deployment (default: testnet).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const network = process.env.BEAM_NETWORK ?? "testnet";
const deploymentPath = join(here, "..", "..", "contracts", "deployments", `${network}.json`);
const d = JSON.parse(readFileSync(deploymentPath, "utf8"));

for (const name of ["BeamGifts", "BeamClaims"]) {
  if (!d[name]?.address || !Number.isInteger(d[name]?.block)) {
    throw new Error(`${deploymentPath}: ${name}.address and ${name}.block are required`);
  }
}

// Event signatures come from the ABI the contracts were compiled to (packages/shared/abi, written
// by `pnpm abi`), so the indexer can never drift from the deployed events.
const abiDir = join(here, "..", "..", "packages", "shared", "abi");
function eventSignature(contract, eventName) {
  const abi = JSON.parse(readFileSync(join(abiDir, `${contract}.json`), "utf8"));
  const ev = abi.find((x) => x.type === "event" && x.name === eventName);
  if (!ev) throw new Error(`${contract} ABI has no ${eventName} event`);
  const params = ev.inputs.map((i) => `${i.type}${i.indexed ? " indexed" : ""} ${i.name}`).join(", ");
  return `${eventName}(${params})`;
}
const events = (contract, names) => names.map((n) => `      - event: "${eventSignature(contract, n)}"`).join("\n");

// Optional: follow the chain head through an RPC in realtime (HyperSync still does historical
// sync). Measured 2026-09-30: every public Monad testnet RPC caps eth_getLogs at 100 blocks and
// throttles bursts, and Envio fell back to HyperSync within ~4s each time. Set
// ENVIO_REALTIME_RPC (and optionally ENVIO_REALTIME_WS) to a dedicated endpoint to enable it.
const realtime = process.env.ENVIO_REALTIME_RPC
  ? {
      url: process.env.ENVIO_REALTIME_RPC,
      ws: process.env.ENVIO_REALTIME_WS,
      pollMs: Number(process.env.ENVIO_REALTIME_POLL_MS ?? 250),
    }
  : null;
const rpcBlock = realtime
  ? `
    rpc:
      - url: "${realtime.url}"
        for: realtime${realtime.ws ? `
        ws: "${realtime.ws}"` : ""}
        polling_interval: ${realtime.pollMs}`
  : "";

const config = `# Generated by scripts/write-config.mjs from contracts/deployments/${network}.json. Do not edit.
name: beam-indexer
disable_default_cross_chain: true
description: Beam live gifts on Monad
handlers: src/handlers
address_format: lowercase
field_selection:
  transaction_fields:
    - hash

contracts:
  - name: BeamGifts
    events:
${events("BeamGifts", ["GiftSent", "GiftSplit"])}
  - name: BeamClaims
    events:
${events("BeamClaims", ["ChatterGiftSent", "BombSent", "Claimed", "Reclaimed"])}

chains:
  - id: ${d.chainId}
    start_block: ${Math.min(d.BeamGifts.block, d.BeamClaims.block)}${rpcBlock}
    contracts:
      - name: BeamGifts
        address: "${d.BeamGifts.address}"
        start_block: ${d.BeamGifts.block}
      - name: BeamClaims
        address: "${d.BeamClaims.address}"
        start_block: ${d.BeamClaims.block}
`;

writeFileSync(join(here, "..", "config.yaml"), config);
console.log(`config.yaml written for ${network} (chain ${d.chainId})`);
