// Copies contract ABIs from Foundry's build output into src/abi.ts so every package uses the
// ABI the deployed bytecode was compiled from. Run `forge build` in contracts/ first.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "..", "contracts", "out");
const names = ["BeamGifts", "BeamClaims"];

let src = "// Generated by scripts/export-abi.mjs from contracts/out. Do not edit.\n";
for (const name of names) {
  const { abi } = JSON.parse(readFileSync(join(out, `${name}.sol`, `${name}.json`), "utf8"));
  const camel = name[0].toLowerCase() + name.slice(1);
  src += `\nexport const ${camel}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
writeFileSync(join(here, "..", "src", "abi.ts"), src);
console.log(`wrote ABIs for ${names.join(", ")}`);
